"""
SensitiveDataChecker - Detects PII/secret leakage in AI output.

Mirrors the TypeScript core's SENSITIVE_DATA_PATTERNS coverage so the same
classes of data exposure (API keys, passwords, private keys, SSN, credit
cards, email, generic PII) are caught on both runtimes.

Patterns are sourced from patterns/regex/sensitive-data-*.json via
scripts/gen_patterns.py — do not edit pattern source in-place; edit the JSON
and re-run the generator. The api-keys family is case-sensitive on purpose
(real prefixes like sk-, AKIA, ghp_, glpat- are constants); the generic
api_key=... assignment lives under passwords with re.IGNORECASE so credential
assignments match regardless of variable casing.

Routes through the AVOIDANCE gate in CLAW: the violation is data leaving the
trust boundary it should not.
"""

from __future__ import annotations

import logging
import re
from typing import Any, Dict, List, Optional

from guardianclaw.detection.checkers.base import BaseChecker, CheckerConfig
from guardianclaw.detection.types import CheckFailureType, DetectionResult

logger = logging.getLogger("guardianclaw.detection.checkers.sensitive_data")


class SensitiveDataChecker(BaseChecker):
    """Checks AI output for sensitive data exposure (PII and secrets)."""

    VERSION = "1.0.0"
    NAME = "sensitive_data_checker"

    # Categories whose patterns are case-sensitive prefix matches.
    SENSITIVE_DATA_API_KEYS = [
        # pattern-sync:start sensitive-data-api-keys
        # generated by scripts/gen_patterns.py from patterns/*.json — do not edit by hand
        r"\b(sk-[a-zA-Z0-9]{10,})\b",
        r"\b(AKIA[A-Z0-9]{16})\b",
        r"\b(ghp_[a-zA-Z0-9]{20,})\b",
        r"\b(glpat-[a-zA-Z0-9_-]{10,})\b",
        # pattern-sync:end sensitive-data-api-keys
    ]

    SENSITIVE_DATA_PRIVATE_KEYS = [
        # pattern-sync:start sensitive-data-private-keys
        # generated by scripts/gen_patterns.py from patterns/*.json — do not edit by hand
        r"-----BEGIN\s+(RSA\s+)?PRIVATE\s+KEY-----",
        r"-----BEGIN\s+OPENSSH\s+PRIVATE\s+KEY-----",
        r"-----BEGIN\s+EC\s+PRIVATE\s+KEY-----",
        # pattern-sync:end sensitive-data-private-keys
    ]

    SENSITIVE_DATA_CREDIT_CARD = [
        # pattern-sync:start sensitive-data-credit-card
        # generated by scripts/gen_patterns.py from patterns/*.json — do not edit by hand
        r"\b4[0-9]{3}[\s-]?[0-9]{4}[\s-]?[0-9]{4}[\s-]?[0-9]{4}\b",
        r"\b5[1-5][0-9]{2}[\s-]?[0-9]{4}[\s-]?[0-9]{4}[\s-]?[0-9]{4}\b",
        r"\b3[47][0-9]{2}[\s-]?[0-9]{6}[\s-]?[0-9]{5}\b",
        # pattern-sync:end sensitive-data-credit-card
    ]

    SENSITIVE_DATA_EMAIL = [
        # pattern-sync:start sensitive-data-email
        # generated by scripts/gen_patterns.py from patterns/*.json — do not edit by hand
        r"\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\b",
        # pattern-sync:end sensitive-data-email
    ]

    # Categories whose patterns are case-insensitive (re.IGNORECASE).
    SENSITIVE_DATA_PASSWORDS = [
        # pattern-sync:start sensitive-data-passwords
        # generated by scripts/gen_patterns.py from patterns/*.json — do not edit by hand
        r"(password|passwd|pwd)\s*[=:]\s*[\x22\x27]?[^\s\x27\x22]{4,}",
        r"(secret[_-]?key|secret|token)\s*[=:]\s*[\x22\x27]?[^\s\x27\x22]{6,}",
        r"my\s+password\s+is[:\s]+[^\s]{4,}",
        r"\b(api[_-]?key\s*[=:]\s*[\x22\x27]?[a-zA-Z0-9_-]{8,})",
        # pattern-sync:end sensitive-data-passwords
    ]

    SENSITIVE_DATA_SSN = [
        # pattern-sync:start sensitive-data-ssn
        # generated by scripts/gen_patterns.py from patterns/*.json — do not edit by hand
        r"\b\d{3}-\d{2}-\d{4}\b",
        r"\bssn\s*(is|:)\s*\d{3}-\d{2}-\d{4}",
        # pattern-sync:end sensitive-data-ssn
    ]

    SENSITIVE_DATA_PII = [
        # pattern-sync:start sensitive-data-pii
        # generated by scripts/gen_patterns.py from patterns/*.json — do not edit by hand
        r"\b\d{3}[-.]?\d{3}[-.]?\d{4}\b",
        r"my\s+phone\s+(is|number)[:\s]+\d{3}",
        r"address[:\s]+\d+\s+\w+\s+(st|street|ave|avenue|blvd|rd|road)",
        r"\b(dob|date\s+of\s+birth)[:\s]+\d{1,2}[/-]\d{1,2}[/-]\d{2,4}",
        r"passport\s+(number|#)?[:\s]+[a-zA-Z0-9]{6,}",
        # pattern-sync:end sensitive-data-pii
    ]

    @property
    def name(self) -> str:
        return self.NAME

    @property
    def version(self) -> str:
        return self.VERSION

    def __init__(self, config: Optional[CheckerConfig] = None) -> None:
        super().__init__(config)
        # Compile each category once. Case-sensitive vs case-insensitive matches
        # the JSON family flags and the TypeScript runtime semantics.
        self._categories: Dict[str, List[re.Pattern[str]]] = {
            "api_keys": [re.compile(p) for p in self.SENSITIVE_DATA_API_KEYS],
            "private_keys": [
                re.compile(p) for p in self.SENSITIVE_DATA_PRIVATE_KEYS
            ],
            "credit_card": [
                re.compile(p) for p in self.SENSITIVE_DATA_CREDIT_CARD
            ],
            "email": [re.compile(p) for p in self.SENSITIVE_DATA_EMAIL],
            "passwords": [
                re.compile(p, re.IGNORECASE)
                for p in self.SENSITIVE_DATA_PASSWORDS
            ],
            "ssn": [re.compile(p, re.IGNORECASE) for p in self.SENSITIVE_DATA_SSN],
            "pii": [re.compile(p, re.IGNORECASE) for p in self.SENSITIVE_DATA_PII],
        }

    def check(
        self,
        output: str,
        input_context: Optional[str] = None,
        rules: Optional[Dict[str, Any]] = None,
    ) -> DetectionResult:
        if not isinstance(output, str) or not output:
            return DetectionResult.nothing_detected(self.name, self.version)

        hits: List[str] = []
        for category, patterns in self._categories.items():
            for pattern in patterns:
                if pattern.search(output):
                    hits.append(category)
                    break  # one hit per category is enough for reporting
        if not hits:
            return DetectionResult.nothing_detected(self.name, self.version)

        return DetectionResult(
            detected=True,
            detector_name=self.name,
            detector_version=self.version,
            confidence=0.95,
            category=CheckFailureType.SENSITIVE_DATA_EXPOSURE.value,
            description=f"Sensitive data detected in output: {', '.join(hits)}",
            metadata={"categories": hits},
        )

    def categories_detected(self, text: str) -> List[str]:
        """Convenience helper: list of sensitive-data categories present in text."""
        if not isinstance(text, str) or not text:
            return []
        hits: List[str] = []
        for category, patterns in self._categories.items():
            for pattern in patterns:
                if pattern.search(text):
                    hits.append(category)
                    break
        return hits
