"""Generate language-specific sections from patterns/*.json.

Neutral JSON files in patterns/ are the single source of truth for shared
pattern lists consumed by both the Python SDK and the TypeScript core. This
script rewrites the code blocks between pattern-sync markers in
packages/core/src/patterns.ts, packages/core/src/validator.ts, and
sdk/src/guardianclaw/validators/gates.py so the two sides cannot drift.

Two kinds are supported:

* indicators — lowercased substring lists. Emitted as plain string array
  literals in both languages. Caller-side normalisation
  (`text.lower()` / `toLowerCase()`) handles case.

* regex — regex source strings. Emitted as Python r-strings (compiled
  later by the gate using `re.compile(p, flags)`) and as JavaScript
  regex literals (`/pattern/flags`). Only patterns whose runtime
  semantics match between Python's `re` and JavaScript's `RegExp`
  belong here; divergent patterns stay hand-written on each side.

Usage:
    python scripts/gen_patterns.py           # rewrite files in place
    python scripts/gen_patterns.py --check   # exit non-zero if any file
                                             # would change (used in CI)

Markers, one pair per generated section:

    # pattern-sync:start <name>
    ...
    # pattern-sync:end <name>

The indentation of the start marker is replicated for every emitted line.
Anything outside the marker pair is left untouched, so a single source file
can host several generated sections next to hand-written code.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent.parent
PATTERNS_DIR = ROOT / "patterns"
REGEX_DIR = PATTERNS_DIR / "regex"

TARGETS: tuple[tuple[Path, str], ...] = (
    (ROOT / "packages/core/src/patterns.ts", "ts"),
    (ROOT / "packages/core/src/validator.ts", "ts"),
    (ROOT / "sdk/src/guardianclaw/validators/gates.py", "py"),
    (ROOT / "sdk/src/guardianclaw/detection/checkers/sensitive_data.py", "py"),
)

COMMENT_TOKEN = {"ts": "//", "py": "#"}
STRING_QUOTE = {"ts": "'", "py": '"'}

# Map of v2 flag chars to JavaScript regex flag chars. Python's re module
# takes flags as named constants (re.IGNORECASE, etc.), which the consuming
# code applies at compile time; the JSON 'flags' field is just an opaque
# token from the gate's point of view in Python. The same chars are emitted
# verbatim into JavaScript regex literal flags.
JS_FLAG_MAP = {"i": "i", "m": "m", "s": "s", "u": "u"}


@dataclass(frozen=True)
class PatternFile:
    name: str
    kind: str
    gate: str
    items: tuple[str, ...]
    flags: str
    source: Path


def load_patterns() -> list[PatternFile]:
    files: list[PatternFile] = []
    for path in sorted(PATTERNS_DIR.glob("*.json")):
        if path.name == "schema.json":
            continue
        files.append(_load_one(path))
    if REGEX_DIR.exists():
        for path in sorted(REGEX_DIR.glob("*.json")):
            files.append(_load_one(path))
    # Detect duplicate names early — the marker scan would silently apply
    # the last match otherwise.
    seen: set[str] = set()
    for pf in files:
        if pf.name in seen:
            raise SystemExit(f"duplicate pattern name {pf.name!r} in {pf.source}")
        seen.add(pf.name)
    return files


def _load_one(path: Path) -> PatternFile:
    data = json.loads(path.read_text(encoding="utf-8"))
    required = {"name", "version", "kind", "gate", "items"}
    missing = required - data.keys()
    if missing:
        raise SystemExit(f"{path}: missing required keys: {sorted(missing)}")
    if data["kind"] not in ("indicators", "regex"):
        raise SystemExit(f"{path}: kind must be 'indicators' or 'regex'")
    items = tuple(data["items"])
    if len(set(items)) != len(items):
        raise SystemExit(f"{path}: items contains duplicates")
    flags = data.get("flags", "")
    if data["kind"] == "indicators":
        if flags:
            raise SystemExit(f"{path}: 'flags' is only valid for kind='regex'")
        for item in items:
            if item != item.lower():
                raise SystemExit(
                    f"{path}: indicator item {item!r} must be lowercased"
                )
    else:
        if not isinstance(flags, str):
            raise SystemExit(f"{path}: 'flags' must be a string")
        for ch in flags:
            if ch not in "imsux":
                raise SystemExit(f"{path}: unknown flag {ch!r}")
    return PatternFile(
        name=data["name"],
        kind=data["kind"],
        gate=data["gate"],
        items=items,
        flags=flags,
        source=path,
    )


def render_indicators(items: Iterable[str], indent: str, lang: str) -> list[str]:
    quote = STRING_QUOTE[lang]
    comment = COMMENT_TOKEN[lang]
    lines = [
        f"{indent}{comment} generated by scripts/gen_patterns.py "
        f"from patterns/*.json — do not edit by hand"
    ]
    for item in items:
        escaped = item.replace("\\", "\\\\").replace(quote, "\\" + quote)
        lines.append(f"{indent}{quote}{escaped}{quote},")
    return lines


def render_regex(
    items: Iterable[str], indent: str, lang: str, flags: str
) -> list[str]:
    comment = COMMENT_TOKEN[lang]
    lines = [
        f"{indent}{comment} generated by scripts/gen_patterns.py "
        f"from patterns/*.json — do not edit by hand"
    ]
    if lang == "py":
        # Emit Python r-strings. The JSON-decoded item is already the regex
        # source as it should appear inside an r"...". r-strings do not
        # process escape sequences, so backslashes are passed verbatim and
        # double-quotes cannot be escaped at all — patterns must not contain
        # an unescaped " (we reject them so the parity stays honest).
        for item in items:
            if '"' in item:
                raise SystemExit(
                    f"regex pattern contains a double-quote, which cannot "
                    f"live inside an r-string: {item!r}"
                )
            lines.append(f'{indent}r"{item}",')
    else:
        # Emit JavaScript regex literals. Forward slashes outside of a
        # character class need backslash escaping so they do not terminate
        # the literal; inside a character class the slash is harmless and
        # the extra backslash trips ESLint's no-useless-escape rule. Track
        # bracket depth so we only escape where required.
        js_flags = "".join(JS_FLAG_MAP.get(ch, "") for ch in flags)
        for item in items:
            lines.append(f"{indent}/{_escape_js_regex_literal(item)}/{js_flags},")
    return lines


def _escape_js_regex_literal(pattern: str) -> str:
    """Escape `/` only when outside a `[...]` character class.

    Walks the pattern once. Backslash escapes are passed through verbatim
    (so `\\[` does not open a class). Unescaped `[` opens a class; the
    first unescaped `]` after that closes it.
    """
    out: list[str] = []
    in_class = False
    i = 0
    while i < len(pattern):
        ch = pattern[i]
        if ch == "\\" and i + 1 < len(pattern):
            out.append(ch)
            out.append(pattern[i + 1])
            i += 2
            continue
        if ch == "[" and not in_class:
            in_class = True
        elif ch == "]" and in_class:
            in_class = False
        elif ch == "/" and not in_class:
            out.append("\\")
        out.append(ch)
        i += 1
    return "".join(out)


def render_block(pat: PatternFile, indent: str, lang: str) -> list[str]:
    if pat.kind == "indicators":
        return render_indicators(pat.items, indent, lang)
    return render_regex(pat.items, indent, lang, pat.flags)


def rewrite_source(text: str, name: str, lang: str, block_lines: list[str]) -> str:
    comment = re.escape(COMMENT_TOKEN[lang])
    start_re = re.compile(
        rf"^(?P<indent>[ \t]*){comment}\s*pattern-sync:start\s+{re.escape(name)}\s*$",
        re.MULTILINE,
    )
    end_re = re.compile(
        rf"^(?P<indent>[ \t]*){comment}\s*pattern-sync:end\s+{re.escape(name)}\s*$",
        re.MULTILINE,
    )
    start = start_re.search(text)
    if not start:
        return text
    end = end_re.search(text, start.end())
    if not end:
        raise SystemExit(
            f"{name}: found start marker without matching end marker "
            f"in {lang} source"
        )
    block = "\n".join(block_lines)
    prefix = text[: start.end() + 1]
    suffix = text[end.start() :]
    return prefix + block + "\n" + suffix


def apply(patterns: list[PatternFile], check_only: bool) -> int:
    changed = []
    for path, lang in TARGETS:
        original = path.read_text(encoding="utf-8")
        updated = original
        for pat in patterns:
            # Re-render with the indent that the marker line uses; we read
            # it back from the source on each pass.
            comment = re.escape(COMMENT_TOKEN[lang])
            start_re = re.compile(
                rf"^(?P<indent>[ \t]*){comment}\s*pattern-sync:start\s+"
                rf"{re.escape(pat.name)}\s*$",
                re.MULTILINE,
            )
            m = start_re.search(updated)
            if not m:
                continue
            indent = m.group("indent")
            block = render_block(pat, indent, lang)
            updated = rewrite_source(updated, pat.name, lang, block)
        if updated != original:
            changed.append(path)
            if not check_only:
                path.write_text(updated, encoding="utf-8", newline="\n")
    if check_only and changed:
        rel = [str(p.relative_to(ROOT)) for p in changed]
        sys.stderr.write(
            "pattern-sync: generated output differs from committed source "
            "for:\n  - " + "\n  - ".join(rel) + "\n"
            "Run `python scripts/gen_patterns.py` and commit the result.\n"
        )
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any target file would be rewritten",
    )
    args = parser.parse_args()
    patterns = load_patterns()
    return apply(patterns, check_only=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
