"""Generate language-specific sections from patterns/*.json.

Neutral JSON files in patterns/ are the single source of truth for shared
string-indicator lists consumed by both the Python SDK and the TypeScript
core. This script rewrites the code blocks between pattern-sync markers in
packages/core/src/patterns.ts and sdk/src/guardianclaw/validators/gates.py
so the two sides cannot drift.

Usage:
    python scripts/gen_patterns.py           # rewrite files in place
    python scripts/gen_patterns.py --check   # exit non-zero if any file
                                             # would change (used in CI)

Markers, one pair per generated section:

    # pattern-sync:start <name>
    ...
    # pattern-sync:end <name>

The indentation of the start marker is replicated for every emitted line.
Anything outside the marker pair is left untouched, so a single source file
can host several generated sections next to hand-written code.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent.parent
PATTERNS_DIR = ROOT / "patterns"

TARGETS: tuple[tuple[Path, str], ...] = (
    (ROOT / "packages/core/src/patterns.ts", "ts"),
    (ROOT / "packages/core/src/validator.ts", "ts"),
    (ROOT / "sdk/src/guardianclaw/validators/gates.py", "py"),
)

COMMENT_TOKEN = {"ts": "//", "py": "#"}
STRING_QUOTE = {"ts": "'", "py": '"'}


@dataclass(frozen=True)
class PatternFile:
    name: str
    kind: str
    gate: str
    items: tuple[str, ...]
    source: Path


def load_patterns() -> list[PatternFile]:
    files = []
    for path in sorted(PATTERNS_DIR.glob("*.json")):
        if path.name == "schema.json":
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        required = {"name", "version", "kind", "gate", "items"}
        missing = required - data.keys()
        if missing:
            raise SystemExit(f"{path}: missing required keys: {sorted(missing)}")
        if data["kind"] != "indicators":
            raise SystemExit(f"{path}: only kind='indicators' is supported in v1")
        items = tuple(data["items"])
        if len(set(items)) != len(items):
            raise SystemExit(f"{path}: items contains duplicates")
        for item in items:
            if item != item.lower():
                raise SystemExit(
                    f"{path}: item {item!r} must be lowercased "
                    f"(callers normalise input)"
                )
        files.append(
            PatternFile(
                name=data["name"],
                kind=data["kind"],
                gate=data["gate"],
                items=items,
                source=path,
            )
        )
    return files


def render_items(items: Iterable[str], indent: str, lang: str) -> list[str]:
    quote = STRING_QUOTE[lang]
    comment = COMMENT_TOKEN[lang]
    lines = [
        f"{indent}{comment} generated by scripts/gen_patterns.py "
        f"from patterns/*.json — do not edit by hand"
    ]
    for item in items:
        escaped = item.replace("\\", "\\\\").replace(quote, "\\" + quote)
        suffix = "," if lang == "ts" else ","
        lines.append(f"{indent}{quote}{escaped}{quote}{suffix}")
    return lines


def rewrite_source(text: str, name: str, lang: str, items: Iterable[str]) -> str:
    comment = re.escape(COMMENT_TOKEN[lang])
    start_re = re.compile(
        rf"^(?P<indent>[ \t]*){comment}\s*pattern-sync:start\s+{re.escape(name)}\s*$",
        re.MULTILINE,
    )
    end_re = re.compile(
        rf"^(?P<indent>[ \t]*){comment}\s*pattern-sync:end\s+{re.escape(name)}\s*$",
        re.MULTILINE,
    )
    start = start_re.search(text)
    if not start:
        return text
    end = end_re.search(text, start.end())
    if not end:
        raise SystemExit(
            f"{name}: found start marker without matching end marker "
            f"in {lang} source"
        )
    indent = start.group("indent")
    block = "\n".join(render_items(items, indent, lang))
    # Preserve the exact marker lines and the newline that follows start.
    prefix = text[: start.end() + 1]  # include the trailing \n after start
    suffix = text[end.start() :]
    return prefix + block + "\n" + suffix


def apply(patterns: list[PatternFile], check_only: bool) -> int:
    changed = []
    for path, lang in TARGETS:
        original = path.read_text(encoding="utf-8")
        updated = original
        for pat in patterns:
            updated = rewrite_source(updated, pat.name, lang, pat.items)
        if updated != original:
            changed.append(path)
            if not check_only:
                path.write_text(updated, encoding="utf-8", newline="\n")
    if check_only and changed:
        rel = [str(p.relative_to(ROOT)) for p in changed]
        sys.stderr.write(
            "pattern-sync: generated output differs from committed source "
            "for:\n  - " + "\n  - ".join(rel) + "\n"
            "Run `python scripts/gen_patterns.py` and commit the result.\n"
        )
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any target file would be rewritten",
    )
    args = parser.parse_args()
    patterns = load_patterns()
    return apply(patterns, check_only=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
