import { Shield, Database, Bot, Wallet, Zap, type LucideIcon } from 'lucide-react'

export interface Product {
  slug: string
  name: string
  tagline: string
  description: string
  icon: LucideIcon
  color: string
  features: string[]
  useCases: string[]
  codeExample: {
    language: string
    code: string
  }
}

export const products: Product[] = [
  {
    slug: 'memory-shield',
    name: 'Memory Shield',
    tagline: 'Cryptographic protection against memory injection',
    description: `Memory Shield protects AI agent memory from manipulation attacks using
HMAC-based integrity verification. Based on Princeton CrAIBench research showing 85%
attack success rate on unprotected agents, it signs memory entries when writing and
verifies signatures before use, preventing context poisoning and memory injection.`,
    icon: Shield,
    color: 'claw',
    features: [
      'HMAC-SHA256 integrity signing',
      'Per-entry tamper detection',
      'Trust scores by source (user, API, social media)',
      'Content validation before signing (v2.0)',
      'SafeMemoryStore for automatic sign/verify',
    ],
    useCases: [
      'Long-running autonomous agents',
      'Multi-agent communication',
      'Crypto trading agents (protect against address injection)',
      'Agents with persistent memory across sessions',
    ],
    codeExample: {
      language: 'python',
      code: `from guardianclaw.memory import (
    MemoryIntegrityChecker,
    MemoryEntry,
    MemorySource,
)

# Initialize with secret key
checker = MemoryIntegrityChecker(secret_key="your-secret-key")

# Sign memory entries when writing
entry = MemoryEntry(
    content="User requested transfer of 10 SOL",
    source=MemorySource.USER_DIRECT,
)
signed = checker.sign_entry(entry)

# Verify before using
result = checker.verify_entry(signed)
if result.valid:
    # Safe to use - trust_score based on source
    process_memory(signed.content)
else:
    # Memory was tampered with!
    print(f"Tampering detected: {result.reason}")`,
    },
  },
  {
    slug: 'database-guard',
    name: 'Database Guard',
    tagline: 'SQL injection prevention for AI agents',
    description: `Database Guard validates SQL queries generated by AI agents before execution.
It prevents SQL injection, detects sensitive data access, and enforces table/operation
restrictions. Reference: OWASP ASI03 (Identity and Privilege Abuse).`,
    icon: Database,
    color: 'blue',
    features: [
      'SQL injection pattern detection',
      'Table allowlist/blocklist enforcement',
      'Sensitive column detection (passwords, SSN, credit cards)',
      'Row limit enforcement',
      'Preset policies (STRICT, MODERATE, PERMISSIVE)',
    ],
    useCases: [
      'Text-to-SQL agents',
      'Data analysis assistants',
      'Business intelligence bots',
      'Customer service with DB access',
    ],
    codeExample: {
      language: 'python',
      code: `from guardianclaw.database import DatabaseGuard

# Configure allowed tables and limits
guard = DatabaseGuard(
    allowed_tables={"orders", "products"},
    max_rows_per_query=1000,
    require_where_clause=True,
)

# Validate AI-generated query
query = agent.generate_query("Show me orders from last week")
result = guard.validate(query)

if result.allowed:
    # Execute the query
    db.execute(query)
else:
    print(f"Blocked: {result.reason}")
    for v in result.violations:
        print(f"  - {v.description}")`,
    },
  },
  {
    slug: 'humanoid-safety',
    name: 'Humanoid Safety',
    tagline: 'ISO/TS 15066 compliant safety for robots',
    description: `Humanoid Safety implements CLAW validation for humanoid robots with ISO/TS 15066
compliant contact force limits. Includes 29 body region force limits, balance monitoring,
and pre-configured presets for Tesla Optimus, Boston Dynamics Atlas, and Figure 02.`,
    icon: Bot,
    color: 'orange',
    features: [
      'ISO/TS 15066 contact force limits (29 body regions)',
      'Pre-configured presets (Tesla Optimus, Atlas, Figure 02)',
      'Balance monitoring and fall detection',
      'CLAW validation for humanoid actions',
      'Human proximity safety checks',
    ],
    useCases: [
      'Personal care robots',
      'Industrial humanoids',
      'Collaborative manipulation',
      'Human-robot interaction research',
    ],
    codeExample: {
      language: 'python',
      code: `from guardianclaw.safety.humanoid import (
    HumanoidSafetyValidator,
    HumanoidAction,
    BodyRegion,
    tesla_optimus,
)

# Create validator with Tesla Optimus constraints
validator = HumanoidSafetyValidator(
    constraints=tesla_optimus(environment="personal_care"),
)

# Validate an action
action = HumanoidAction(
    joint_velocities={"left_elbow_pitch": 0.5},
    expected_contact_force=25.0,
    contact_region=BodyRegion.CHEST_STERNUM,
    worth="Hand object to user",
    is_collaborative=True,
)

result = validator.validate(action)
if result.is_safe:
    print("Action approved")
else:
    print(f"Blocked: {result.reasoning}")`,
    },
  },
  {
    slug: 'fiduciary-ai',
    name: 'Fiduciary AI',
    tagline: 'Ensuring AI acts in your best interest',
    description: `Fiduciary AI validates that AI agents act with loyalty and care toward users,
following the six-step fiduciary framework from ACM FAccT 2023 research. It detects
conflicts of interest, ensures transparency, and protects user confidentiality.`,
    icon: Wallet,
    color: 'purple',
    features: [
      "Duty of Loyalty validation (user's best interest)",
      'Duty of Care validation (competence and diligence)',
      'Conflict of interest detection',
      'Transparency requirement enforcement',
      'Confidentiality protection',
    ],
    useCases: [
      'AI advisors and assistants',
      'Recommendation systems',
      'Healthcare AI agents',
      'Legal AI assistants',
    ],
    codeExample: {
      language: 'python',
      code: `from guardianclaw.fiduciary import FiduciaryValidator, UserContext

# Create validator
validator = FiduciaryValidator()

# Define user context
user = UserContext(
    goals=["save for retirement"],
    risk_tolerance="low",
    constraints=["no crypto", "ethical investments only"],
)

# Validate action against fiduciary duties
result = validator.validate_action(
    action="Recommend high-risk cryptocurrency investment",
    user_context=user,
)

if not result.compliant:
    print("Fiduciary violation detected!")
    for v in result.violations:
        print(f"  - {v.duty.value}: {v.description}")`,
    },
  },
  {
    slug: 'transaction-simulator',
    name: 'Transaction Simulator',
    tagline: 'Validate Solana transactions before execution',
    description: `Transaction Simulator validates blockchain transactions BEFORE execution.
It simulates swaps via Jupiter API, detects honeypots and rug pulls via GoPlus API,
and estimates slippage to protect AI agents from malicious tokens and failed transactions.`,
    icon: Zap,
    color: 'cyan',
    features: [
      'Transaction simulation via Solana RPC',
      'Honeypot and rug pull detection',
      'Slippage estimation (Jupiter API)',
      'Token security analysis (GoPlus API)',
      'Liquidity pool analysis',
    ],
    useCases: [
      'DeFi trading agents',
      'Token swap automation',
      'Crypto portfolio managers',
      'Arbitrage bots',
    ],
    codeExample: {
      language: 'python',
      code: `from guardianclaw.integrations.coinbase import TransactionValidator

# Initialize simulator for Solana
simulator = TransactionSimulator(
    rpc_url="https://api.mainnet-beta.solana.com",
    goplus_api_key=None,  # Optional, free tier available
)

# Simulate a token swap before execution
result = await simulator.simulate_swap(
    input_mint="So11111111111111111111111111111111111111112",  # SOL
    output_mint="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",  # USDC
    amount=1_000_000_000,  # 1 SOL in lamports
)

if result.is_safe:
    print(f"Safe to swap. Slippage: {result.slippage_bps} bps")
else:
    for risk in result.risks:
        print(f"Risk: {risk.factor.value} - {risk.description}")`,
    },
  },
]

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductColors(color: string): { bg: string; text: string; border: string } {
  const colors: Record<string, { bg: string; text: string; border: string }> = {
    claw: {
      bg: 'bg-claw-500/10',
      text: 'text-claw-500',
      border: 'border-claw-500/20',
    },
    blue: {
      bg: 'bg-blue-500/10',
      text: 'text-blue-500',
      border: 'border-blue-500/20',
    },
    orange: {
      bg: 'bg-orange-500/10',
      text: 'text-orange-500',
      border: 'border-orange-500/20',
    },
    purple: {
      bg: 'bg-purple-500/10',
      text: 'text-purple-500',
      border: 'border-purple-500/20',
    },
    cyan: {
      bg: 'bg-cyan-500/10',
      text: 'text-cyan-500',
      border: 'border-cyan-500/20',
    },
  }
  return colors[color] || colors.claw
}
